### ISSUE TITLE
Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc

### ISSUE THREAD

**Issue by popdukes** [finndev/PokeBuddy#1242]
whats up guys?! ive been trying everything to get this running again. ive tries VPN, resetting my modem, just everything. it will run for about a few mins then i get the errors below. i have my walk set to 11km, no incubators, farm and catch. i dont know what else to do. my legit account seems to have gotten banned due to GPS issues. took me a month to get to level 22 then pow i get the failed to connect. which pissed me off and here i am. im not taking another month to get to level 22. anyway, i tried following a few other post here but the issues continue. any help or other bots would help. i tried doing the hackemon but i just cant get it to run. i DL java8 but you have to change some many thing to get it to work.
[P - 12:38:21] [Catch Pokemon] No Pokemon nearby
[P - 12:38:22] [Transferring Pokemons] Transferring Pokemon away: Pidgey (CP: 45)!
[P - 12:38:44] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:38:45] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:25] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:27] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:27] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:28] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:47] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:49] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:49] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:39:50] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:40:02] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:40:04] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:40:04] [Farm Pokestops - ERROR]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at t0AED0t)J8rUd$xJ\.IG'`4~9-.rozTR{Tq-gm<3X~(3U8oO/!Q\&`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at t0AED0t)J8rUd$xJ\.IG'`4~9-.8=DUuxb\[m1yQ;>DVf^~Re\\A8"`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gwb\[;@5LsO2nL\&X)e"x-E\&{\[.2b@$(_"m{x\*dQCqL~m@W=!KF!`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YN~}#vC?6/g!6Qt=1ldzZ6S\*'.4(A>x9fDZkvA}|4>KcmA(P$b".MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 12:40:05] [Farm Pokestops] Updating Pokestops...
[P - 12:40:09] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:40:11] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:40:23] Retrying request https://pgorelease.nianticlabs.com/plfe/624/rpc
[P - 12:40:25] Retrying request https://pgorelease.nianticlabs

**Comment by TheProblem** [comment]
I think you are banned

**Comment by popdukes** [comment]
i can still log into the go account with no issues. i keep restarting buddy then its stops after like 10 mins

**Comment by popdukes** [comment]
its only level 6 nothing crazy

**Comment by xReVoLT-iTheme** [comment]
No... Click the link below and you'll see this:

<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>Ref A: BD5BEFD74EBC4EEA86BA8D02FADABA07 Ref B: F4C21FB64F9D76DF0D2332C6F63BDACC Ref C: Sat Aug 20 11:42:27 2016 PST

https://pgorelease.nianticlabs/

Next time, click the links... Servers unavailable. Close the thread/issue.

**Comment by popdukes** [comment]
got it!!! thanks!!!
