### ISSUE TITLE
not catching pokemon

### ISSUE THREAD

**Issue by ch4chis** [finndev/PokeBuddy#1280]
since today the  pokebuddy is not catching any pokemon, it isnt even trying , is just me ?

**Comment by bloodygear21** [comment]
Also got this issue.. Another issue is, once Pokestop is farmed, the indicator in the map of that Pokestop will disappear. Unlike previously it will turn red. 

Below is the error I got.
[P - 09:45:51] [Farm Pokestops - ERROR]: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: '‍​‪⁪‫‌⁬⁮‭⁭​⁮⁯‪‮‍‪⁮‬⁪⁭​⁬⁫⁪​​‍⁫‬‮‪⁮‏⁪‮⁮‭‌‎‮' does not contain a definition for 'CalculatePokemonPerfection'
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by darkraigo18** [comment]
yeah, they updatd it and put the IV's of the pokemon you have, but it is not catching any pokemon

**Comment by finndev** [comment]
fixed, restart the bot to get last update please (in ~5min)
