### ISSUE TITLE
Farm Pokestops - ERROR

### ISSUE THREAD

**Issue by pistache60** [finndev/PokeBuddy#1307]
[P - 20:57:24] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at ‎‎‌​⁫‮‪⁫⁭‏‬⁫‌⁮‬​‏⁬‫‬⁪⁫‬​​‫‌⁫⁪‮⁯‍⁬‌‬​⁬‪‎‎‮.‍‏⁭​‬‏⁮‍⁪‫‫‏‪‍‎‫‍‎⁯​‎​⁫‭‮‪⁭‫‍‪⁯⁬‏⁯‬‏‎⁮⁫‌‮.‎⁬⁬‪‮‮‍⁭‮‏⁭⁭‏‫⁬‌‬⁫⁫⁫‍‪‌⁪​​‮⁮‬‬⁫‫‍‍‫‏‪‍‪‬‮()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at ‎‎‌​⁫‮‪⁫⁭‏‬⁫‌⁮‬​‏⁬‫‬⁪⁫‬​​‫‌⁫⁪‮⁯‍⁬‌‬​⁬‪‎‎‮.⁮‌⁮‫‮⁯‎⁬⁫‪‭‪‭⁭‮‌​⁯‏‎‍‍⁮⁬‭⁮‬‭‎⁬‮⁬⁪⁮‬‪‍⁪‏⁪‮(Double lat)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.UpdateGMapsMarker(Double lat, Double lng, Int64 cooldownCompleteTimestampMs)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

thank you to do something about this problem.

**Comment by babidee143** [comment]
Got the same problem

**Comment by kumaski** [comment]
me too
