### ISSUE TITLE
Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/644

### ISSUE THREAD

**Issue by warrlock11** [finndev/PokeBuddy#1310]
help

**Comment by warrlock11** [comment]
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by ST1998** [comment]
You do not worry, it's a normal thing. Usually I had happened to me when I was in a PokéSpot, but seemed to be invisible and I had not counted.
