### ISSUE TITLE
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at PokeBuddy.Core.Routine.<>c.<b__16_3>d.MoveNext()

### ISSUE THREAD

**Issue by warrlock11** [finndev/PokeBuddy#1311]

**Comment by Ray-PoGo-NL** [comment]
[P - 22:46:38] [Transferring Pokemons] Transferring Pokemon away: Paras (CP: 512)!
[P - 22:47:02] [Farm Pokestops] Spinning Pokestop: 'Flower and Thorns'
[P - 22:47:03] [Farm Pokestops] Success -> Received XP: 50
[P - 22:47:03] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at ⁭‍‬‮‮‌⁪⁯‬‏⁬‍⁪‍‍⁯⁭‫‪⁫‪⁬‌⁮‎‍⁪⁮​‌⁪‪‮​‭‏‬‮‭‪‮.‎⁯‬‎⁯⁬‫‬‪‏‮​⁫⁮‭‬‪‪⁮‫‎⁭‍⁭⁮⁮⁭‬⁬⁪‭‎‭⁮‮‫‫‍‪‮‮.⁭⁭⁪⁬⁫‌⁭‮‎‏‫‏⁯⁪‮⁮⁮‌‭‬⁭‍‬‏‎‏‍⁫⁭⁯⁮‌‬‎‮​⁮⁮⁮‌‮()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at ⁭‍‬‮‮‌⁪⁯‬‏⁬‍⁪‍‍⁯⁭‫‪⁫‪⁬‌⁮‎‍⁪⁮​‌⁪‪‮​‭‏‬‮‭‪‮.​​‭⁯⁫‬⁬‭‌‪‎⁬‎‌⁬⁮‮‪‬⁯⁭‪‭‍⁫⁪⁬⁭‮‏⁬⁫⁯⁯‭‌‮‫⁯⁬‮(Double lat)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.UpdateGMapsMarker(Double lat, Double lng, Int64 cooldownCompleteTimestampMs)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
