### ISSUE TITLE
Error in Pokebot

### ISSUE THREAD

**Issue by kalaharami** [finndev/PokeBuddy#186]
[P - 21:58:35] [Catch Pokemon - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by kalaharami** [comment]
Not sure how to fix this but the bot wont work it just gives me this error message and keeps saying updating... over and over again. I have tried reinstalling a few times.

**Comment by Vanethir** [comment]
Tried to reboot your PC as well?

**Comment by aniketk11** [comment]
I have the same issue. Gives the same error after a while and gets stuck. I need to stop and start it manually everytime.

**Comment by aniketk11** [comment]
Btw. Please can someone tell me where the logs are kept? I cant find them in the PokeBuddy directory.
