### ISSUE TITLE
stil not working for me

### ISSUE THREAD

**Issue by bertje123** [finndev/PokeBuddy#354]
the only thing it does is just walking. not farming pokestops and not catching pokemon.
help?

**Comment by Deuxgod** [comment]
Try to redownload it and set it again. It's working fine.

**Comment by AhmadS12** [comment]
Clean install it again.

**Comment by bertje123** [comment]
already did that

**Comment by gersonalpha** [comment]
try another account, you have been baned, try do not abuse of velocity

**Comment by bertje123** [comment]
im not  baned. i can play on my phone and i started the bot near my location.

**Comment by RobJansen** [comment]
I can't find pokestops or pokemons at other places then: 
Lat: -33.865143
Lon: 151.209900
Maybe if you use them it works?

**Comment by bertje123** [comment]
got it to work. thanks for the help!

**Comment by Raigosh** [comment]
How you solved it? i still got the same problem.

**Comment by TheWonderSpud** [comment]
How did you get it to work? It's still not working for me.. :(

**Comment by AntiquaBellator** [comment]
Mines just keeps saying 'updating' over and over...

**Comment by TheWonderSpud** [comment]
@bertje123 How did you get it to work? Please tell us! :O

**Comment by AntiquaBellator** [comment]
Yeah, tell us! haha I can't get it to do anything other than spawn in and stand still... won't even catch pokemon.

**Comment by TheWonderSpud** [comment]
Mine just walks, transfers Pokemon and recycles items

**Comment by Raigosh** [comment]
just walk and recycles...

**Comment by AntiquaBellator** [comment]
Mine isn't even walking :O I uninstalled, reinstalled, set it up again and nothing :/ it registers I'm in a location and says it's going to move to new coordinates but then just says 'updating' over and over. Won't move, won't transfer pokemon, won't recycle items :/ hmm...

**Comment by bertje123** [comment]
I reinstalled it 3 times. every time I download it I got a different version. the last time it worked. make sure you delete your old version before installing a new one

**Comment by TheWonderSpud** [comment]
I get
"Failed to download file: PokeBuddy.Core.dll. Retry later."
:(

**Comment by TheWonderSpud** [comment]
"C:\Users\Alex\Desktop\Tryte FPS Pack\Poke\PokeBuddy-master.zip: Cannot create C:\Users\Alex\Desktop\Tryte FPS Pack\Poke\PokeBuddy-master\Core\PokeBuddy.Core.dll
!   Access is denied."

I'm getting this error when I extract the ZIP file..?!

**Comment by bertje123** [comment]
try to download it again

**Comment by curtiola** [comment]
Access is denied lol change your user account settings

**Comment by Raigosh** [comment]
Ok, mine started to work, after a some reinstalls

**Comment by TheWonderSpud** [comment]
@curtiola How???

**Comment by curtiola** [comment]
What's your OS?

**Comment by TheWonderSpud** [comment]
@curtiola Windows 10

**Comment by curtiola** [comment]
Try this how to if you have win 7 or newer
https://www.google.ca/url?sa=t&source=web&rct=j&url=http://www.howtogeek.com/howto/windows-vista/disable-user-account-control-uac-the-easy-way-on-windows-vista/&ved=0ahUKEwjazp7U9K_OAhVl0YMKHZmYB0MQFggiMAI&usg=AFQjCNFeHPMxs0R6TOpLo_VKQpcB2l5q0g&sig2=mj5e0FUwrPXErgb0_yFVDw

**Comment by bertje123** [comment]
im on windows 10. just reinstal it

**Comment by curtiola** [comment]
If that doesn't work, is your profile the administrator on your computer? You need to be admin and then right click on the folder you're having trouble accessing(downloads if that's where pokebuddy.zip is), go to properties, security tab, and add full permissions to homeusers

**Comment by curtiola** [comment]
It might just be denying access because you have it on the desktop (it looks like you do anyway) maybe you just need to extract this in another location and create a shortcut instead of copying it all to desktop

**Comment by TheWonderSpud** [comment]
@curtiola I have full permissions. I have tried the method on the link you sent me and I still get this error when I extract the ZIP.

**Comment by curtiola** [comment]
@bertje123 he's having access issues, he can't install of he can't unzip, it's nothing to do with pokebuddy

**Comment by TheWonderSpud** [comment]
Should I reinstall WinRAR?

**Comment by TheWonderSpud** [comment]
I have all anti-virus programs off also...

**Comment by curtiola** [comment]
Try extracting somewhere other than the desktop, also I don't use winrar,  just right click and click extract all

**Comment by TheWonderSpud** [comment]
@curtiola Can you do that without WinRAR?

**Comment by curtiola** [comment]
Yeah, but I think the problem is the file you want to extract is on the desktop tbh

**Comment by TheWonderSpud** [comment]
@curtiola Ok I will try somewhere else

**Comment by curtiola** [comment]
If it still doesn't work, check if the folder pokebuddy.zip is in is set to read-only, that would do it

**Comment by curtiola** [comment]
Success? xD

**Comment by TheWonderSpud** [comment]
@curtiola I did it in my documents without WinRAR I just clicked "Extract all..."

Everything went fine until I tried to launch PokeBuddy and I get this error:

"Unexpected error during update routine!

Routine: ","
Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\Alex\Documents\%PGOBot\PokeBuddy-master(3)\PokeBuddy-master\PokeBuddy\Core\PokeBuddy.Core.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 buffersize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at (htap gnirtS).
   at .(sgra 2'yranoitciD ,iu wodniWtadpU)
   at PokeBuddy.Views.UpdateWindow.)sgra tcejbO("

**Comment by TheWonderSpud** [comment]
And no, it isn't set to Read Only

**Comment by curtiola** [comment]
Oh damn lol right click my documents and see if all the permissions are checked for your profile or homeusers in the security tab, or maybe the folder is read only(but I doubt it)

**Comment by curtiola** [comment]
Hahaha I just read your last comment xP

**Comment by TheWonderSpud** [comment]
@curtiola I checked to see permissions and I have all permissios except "Special permissions"

**Comment by curtiola** [comment]
OK well I'm running out of ideas xD I'm sorry if this doesn't help or is promoting something (I didn't watch it) but this video might help https://www.google.ca/url?sa=t&source=web&rct=j&url=http://m.youtube.com/watch%3Fv%3D3dE4Rz-baFg&ved=0ahUKEwi7hcew-6_OAhVm4oMKHbXzASEQtwIIHjAB&usg=AFQjCNGGbC0m88gpUXK42c2Dl-xN5wR5dg&sig2=TmVTEhCGpZIkBXz7Oiq8nQ

**Comment by TheWonderSpud** [comment]
@curtiola I don't even have a "Local Users and Groups" tab

Ughhhhhhh :/

**Comment by curtiola** [comment]
As dumb of a question as it is, did you try try run as admin? Lol..

**Comment by TheWonderSpud** [comment]
@curtiola Uhhhhhhhh n.. n... no.... Omg...

If this works I'm going to facepalm so hard

**Comment by curtiola** [comment]
Haha well I hope it does

**Comment by TheWonderSpud** [comment]
Nope it still hasn't worked @curtiola 
:cry:

**Comment by curtiola** [comment]
Oh, maybe add permissions for everyone? It looks like it's not you that needs permission but the prpgram itself or connection it makes to update the files, I'm grasping at straws here haha

**Comment by curtiola** [comment]
And if you haven't already, add the exe to exceptions on your AV

**Comment by curtiola** [comment]
Or windows firewall of you even have that active still xD

**Comment by One2Triple** [comment]
@curtiola I have the exact same error, tried extracting on desktop, update error, tried on my documents, update error, tried on downloads folder, update error. Yes I ran it as administrator, all folders have full permissions.

**Comment by curtiola** [comment]
Try copying pokebuddy.exe and placing it in the pokebuddy-master folder and then running, I know that solved someone's problem a while back but I can't remember what it was lol

**Comment by curtiola** [comment]
Beyond that, I don't know, I'm racking my brain, if it's not permissions or a firewall or something like that then I'm at a loss, sure am glad I didn't get windows 10 though haha

**Comment by One2Triple** [comment]
@curtiola Nope, nothing. It's wierd because before the api update it worked just fine :/

**Comment by curtiola** [comment]
Hm, well it seems like it's just pokebuddy.core.dll that can't be accessed, try adding that to exceptions on firewall or AV? Check permissions on the users folder? Lol I might not be of much help anymore, my knowledge is limited.. sorry

**Comment by TheWonderSpud** [comment]
@curtiola You've been rly helpful and thankyou so much for the support I hope I'll get it working again soon :)

**Comment by curtiola** [comment]
No problem, I just wish I knew more about windows 10 and and could help get it actually working lol

**Comment by One2Triple** [comment]
@curtiola well I finally got it to work, disabled every single module of security on the AV and added folder exclusion from scanning to PokeBuddy-master and that worked

**Comment by curtiola** [comment]
Oh good I'm glad you fixed it, work for you wonderspud?  Or no such luck? Lol

**Comment by TheWonderSpud** [comment]
@One2Triple Hey dude could you guide me on how to do that please? Thankyou so much

**Comment by curtiola** [comment]
Windows defender/firewall is atrocious, if that's still active it could be your issue

**Comment by curtiola** [comment]
It depends on your AV, open the dashboard, go to settings/preferences, find exceptions and see if you can add directories or files

**Comment by TheWonderSpud** [comment]
How do I disable Windows firewall first of all?

**Comment by curtiola** [comment]
Search for it in the start menu and it should pop up

**Comment by TheWonderSpud** [comment]
Nevermind it's already disabled...

**Comment by One2Triple** [comment]
@TheWonderSpud @curtiola I have Windows defender/firewall overwritten by BitDefender. so I did it there, you could just add on the firewall exceptions, but I think you already did that.

**Comment by curtiola** [comment]
Might have to search windows defender, not sure, no pc nearby atm to see lol

**Comment by curtiola** [comment]
Oh, and your current AV has its firewall disabled? Maybe you have 2? Lol which AV you use?

**Comment by TheWonderSpud** [comment]
I have disabled my AV and my firewall.

**Comment by One2Triple** [comment]
@curtiola can't I just upload the updated version for him to download it, or am I breaking any rules?

**Comment by curtiola** [comment]
Hm, not sure what to try next lol I would default to checking permissions and stuff again but if you're sure that's all in order I'm out of ideas again Dx

**Comment by TheWonderSpud** [comment]
@One2Triple That'd be fantastic if you could althought I'm new here and have no idea about rules... :/

**Comment by curtiola** [comment]
You could do that @one2triple it's not against the rules while it's free as far as I know but I'm not 100% sure

**Comment by curtiola** [comment]
Legal just says they're not affiliated with Niantic and stuff, no mention of distribution

**Comment by TheWonderSpud** [comment]
@One2Triple Yeah that'd be awesome if you could :D

**Comment by One2Triple** [comment]
@TheWonderSpud Here you go, I had to prepare the folder again to make sure all settings where clear. :) Hope it works! https://mega.nz/#!RsgVGKCK

**Comment by TheWonderSpud** [comment]
@One2Triple "To access this file, you will need it's decryption key. If you do not have the key, contact the creator of the link"

**Comment by One2Triple** [comment]
@TheWonderSpud That's wierd, let me upload it again.

**Comment by curtiola** [comment]
When you compress it, uncheck encrypt for security, if you haven't

**Comment by One2Triple** [comment]
@TheWonderSpud Hope I did it right this time xD
https://mega.nz/#!V4BVgbRK

**Comment by curtiola** [comment]
Did it work @thewonderspud ?

**Comment by TheWonderSpud** [comment]
@One2Triple @curtiola I get the same message..

**Comment by curtiola** [comment]
It sounds like it must be permissions then, I can't think of anything else that it could be haha try running as admin again? Add permissions for my documents/pokebuddy folders for every user category in the security tab?

**Comment by One2Triple** [comment]
@TheWonderSpud do you have any other AV installed? no all AV overwrite Firewall/Defender settings

**Comment by TheWonderSpud** [comment]
@One2Triple This appears on the MEGA site, not a Windows pop=ip or anything. And no, no AV or firewall or anything.

This IS NOT about permissions as the message is on the website. (Mega.nz)
@One2Triple Did you uncheck encrypt for security when compressing the file?

**Comment by curtiola** [comment]
If it's not about the encrypt when you compress, maybe it's something on the website when you upload? I don't know anything about mega but it's possible it has a secure upload option

**Comment by One2Triple** [comment]
@TheWonderSpud gotcha, I know what you mean now
https://mega.nz/#!RsgVGKCK!MXJl1CAox4CpoHafg2EQLTmaV46kXRdJ-IpX-cxFD6M

**Comment by TheWonderSpud** [comment]
@One2Triple How do you open a RAR?

**Comment by curtiola** [comment]
You can use a program like extractnow, or 7zip, I prefer extractnow for rars

**Comment by TheWonderSpud** [comment]
Bad news... It still didn't work... :(

Same error as before when I try to launch PokeBuddy...

"Unexpected error during update routine!

Routine: ","
Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\Alex\Documents\%PGOBot\PokeBuddy-master(3)\PokeBuddy-master\PokeBuddy\Core\PokeBuddy.Core.dll' is denied.
at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 buffersize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
at (htap gnirtS).
at .(sgra 2'yranoitciD ,iu wodniWtadpU)
at PokeBuddy.Views.UpdateWindow.)sgra tcejbO("

**Comment by curtiola** [comment]
Yeah, it's gotta be permissions somewhere, you sure you allowed every security category for my docs and such? And not just for administrator or anything but for homeuser and everyone

**Comment by TheWonderSpud** [comment]
@curtiola The only unchecked permission is "Special Permissions" and idk how to activate that. Is it checked for you?

**Comment by curtiola** [comment]
I couldn't say, my pc is far away, but I just mean everything you can in each collumn, admin, homeusers, everyone, if they're all checked in my documents and pokebuddy folders then I'm stumped lol sorry man, if I had a pc in front of me I might be of more use
