### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by futi666** [finndev/PokeBuddy#359]
[P - 18:38:38] [Navigation] Walking from: -33.8588, 151.20754 to: -33.8586, 151.20774 with a distance of: 18 meters
[P - 18:38:44] [Navigation] Walking from: -33.85876, 151.20758 to: -33.85856, 151.20778 with a distance of: 18 meters
[P - 18:38:50] [Navigation] Walking from: -33.85871, 151.20762 to: -33.85851, 151.20782 with a distance of: 18 meters
[P - 18:38:51] [UI] Updating...
[P - 18:38:56] [Navigation] Walking from: -33.85867, 151.20766 to: -33.85847, 151.20786 with a distance of: 18 

i downloaded new and reinstalled it, can someone help me please? 
(sorry for my bad englisch)

**Comment by Petoux** [comment]
Hello, the BOT is down, because of the new update of Niantic who's changing API's servers, wait a new update x)

**Comment by TheWonderSpud** [comment]
There has been a new update and I am having the same issue as this with the new update installed :(

**Comment by futi666** [comment]
now it works :D

**Comment by TheWonderSpud** [comment]
@futi666 How did you get it to work??? PLEASE TELL ME

**Comment by futi666** [comment]
closed and re-openend

**Comment by Petoux** [comment]
Yeah, the BOT is working right now

**Comment by futi666** [comment]
![fg](https://cloud.githubusercontent.com/assets/20840876/17463854/f24b0e80-5cd0-11e6-872e-beb65a3d4532.png)

**Comment by TheWonderSpud** [comment]
It's still not working for me HELPPPP :(
No pokestops are displaying and no pokemon can be found

**Comment by Petoux** [comment]
@futi666 what is your location ? a lot of pokestops ! :D

**Comment by futi666** [comment]
sydney opera house
-33.859012
151.207323

**Comment by TheWonderSpud** [comment]
Guys it isn't working :(

**Comment by futi666** [comment]
@TheWonderSpud try it a few times dude :)

**Comment by TheWonderSpud** [comment]
I'm trying another clean install

**Comment by Cree666** [comment]
What file do i have to download?

Core	Update PokeBuddy	2 hours ago
Dependencies	Update PokeBuddy	2 hours ago
Loader	Update PokeBuddy	2 hours ago
Niantic	Update PokeBuddy	10 days ago
Profiles	Update PokeBuddy	10 days ago
Dependencies.json	Update PokeBuddy	2 hours ago
PokeBuddy.exe.config	Update PokeBuddy	10 days ago
PokeBuddy.zip	new zip-2	2 hours ago
README.md	Update README.md (#255)	3 days ago
settings.json	new default settings	6 days ago

Please help :)

**Comment by futi666** [comment]
hmh mine works fine after reinsalling it and start it 3-5 times...

**Comment by Petoux** [comment]
@Cree666 All, just click clone or download, and click download ZIP

**Comment by TheWonderSpud** [comment]
"C:\Users\Alex\Desktop\Tryte FPS Pack\Poke\PokeBuddy-master.zip: Cannot create C:\Users\Alex\Desktop\Tryte FPS Pack\Poke\PokeBuddy-master\Core\PokeBuddy.Core.dll
!   Access is denied."

When I extract the ZIP file :(

**Comment by TheWonderSpud** [comment]
Then it says "Failed to download PokeBuddy.Core.dll. Try again later."

**Comment by JCortexs** [comment]
just dont extract the zip open it and use the exe.I just downloaded and it works for me! .

**Comment by Cree666** [comment]
@Petoux When I click the *.exe in the "Loader" folder, it does nothing. If I copy the *.exe in the main folder it opens, but generates errors:

[P - 19:18:27] [Catch Pokemon - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 19:18:28] [Navigation] Walking from: 50.9282, 11.58268 to: 50.9284, 11.58288 with a distance of: 16 meters
[P - 19:18:31] [UI] Updating...
[P - 19:18:33] Stopping...
[P - 19:18:37] [UI] Updating...

**Comment by JackSbirrow** [comment]
When I try with PTC it says: Retrying request https://pgorelease.nianticlabs.com/plfe/rpc
If I try with Google it says: [Error] GoogleAuthError: Object reference not set to an instance of an object.

Any solution?

**Comment by kenwang911** [comment]
@futi666  can you please help how fix this issue, [UI] Updating.......   I had the same issue now....tried deleted and redownload, change locations, restart the programme few times....but still not working....
