### ISSUE TITLE
UI Updating (Request log)

### ISSUE THREAD

**Issue by PromethiumFire** [finndev/PokeBuddy#405]
[P - 00:12:26] [UI] Updating...
[P - 00:12:28] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:12:28] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:12:33] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:12:38] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:12:59] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:13:59] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:13:59] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:14:00] [Catch Pokemon - ERROR]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at f$_T6Mr_W\[y-FC->#WFrbxcb#.Ne>C`>$|GL%p?lNqy\*w"\[7_<-`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at f$_T6Mr_W\[y-FC->#WFrbxcb#.iQ%Iv%5Sz!8S!n|04JibJRiZ\,`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ;MWzYZd<1PwFW-#dcT<NAO#U".rVT47K\.tL?X>PGg>B%ReM\\t<!`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at 2nwGCCkgy62c1W721}N \\\\80\&.KrvGQ<#DJ6\*GF#_WQyP6AdHF\..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 00:14:00] [Farm Pokestops - ERROR]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at f$_T6Mr_W\[y-FC->#WFrbxcb#.Ne>C`>$|GL%p?lNqy\*w"\[7_<-`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at f$_T6Mr_W\[y-FC->#WFrbxcb#.iQ%Iv%5Sz!8S!n|04JibJRiZ\,`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ;MWzYZd<1PwFW-#dcT<NAO#U".o6'c81#_W0EQna#P B"^LVM<$`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at 8'n(R#^Y\.cBGRT>XHY\]p7s<Q$.gz$ _Tr{3KkEqN35Cy$FjxMi$.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at -\.lDD\.mCww'1LIgA<`7i'}bm.-\,i\,@rs@CSRCSXoq`d!Bei\&Q.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 00:14:03] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:14:06] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc
[P - 00:14:11] [UI] Updating...
[P - 00:14:12] [Farm Pokestops] Populated Pokestops
[P - 00:14:15] Retrying request https://pgorelease.nianticlabs.com/plfe/196/rpc

**Comment by PromethiumFire** [comment]
PokeBuddy is now stuck updating?

**Comment by stavrosian** [comment]
same thing for me, it was working perfectly until exactly 3 minutes ago,

**Comment by PromethiumFire** [comment]
just click stop then start again. It's either just a bug or Niantic, Inc are up to something.

**Comment by Dropholion** [comment]
I've tried restarting about ten times, even my PC. It's Niantic I think. It was nice while it lasted.

**Comment by futi666** [comment]
my bot works fine

**Comment by PromethiumFire** [comment]
Mine is also working fine now, I literally clicked stop then start and it was fine.

**Comment by smqh-github** [comment]
i have the same thing
