### ISSUE TITLE
please help catching poke error none pokeball related or soft ban

### ISSUE THREAD

**Issue by Enviouse** [finndev/PokeBuddy#473]
hi guy i downloaded the new updated pokebuddy last night apon release i tryed it for a bit it was working great useall 40 k exp per hr n catching pokmon i turned it off went to bed i just turned it on a few hrs ago it cought 5 pokemon then after that i keep getting this msg ever encounter of a pokemon
Error pokemon Encounter failed
then in red i get this msg until i turn off the catch pokemon function

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 17:10:41] [Catch Pokemon] Catching a lured pokemon...
[P - 17:10:41] [Farm Pokestops - ERROR]: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 17:10:44] [Catch Pokemon] Catching a lured pokemon...
[P - 17:10:44] [Farm Pokestops - ERROR]: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 17:10:54] [Catch Pokemon] Catching a lured pokemon...
[P - 17:10:55] [Farm Pokestops - ERROR]: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 17:10:57] [Farm Pokestops] Populated Pokestops
[P - 17:10:58] [Catch Pokemon] Catching a lured pokemon...
[P - 17:10:58] [Farm Pokestops - ERROR]: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

If anyone can help i would really appreciate poke stops work fine but no pokemon means 6k exp per hr not the 40k

**Comment by pokemonloverx333** [comment]
i always check coords walk speed etc of this , also if i use google account  i relog in my browser restart the program and if it still doenst work i just always delete my settings an d restart

**Comment by Enviouse** [comment]
What do u mean relog in my browser

**Comment by Enviouse** [comment]
i have my player in melb lots of pokestops my walk speed is at 10 n this happens on mulitple accounts

**Comment by CaptainArghh** [comment]
First of all, make sure you have regular pokeballs on you, as the great and ultra ball doesn't work currently. If that doesn't solve your issue, make sure the pokebuddy.exe is in the same folder as the other files that followed the download (Not sure if this matters much, but worth a try). Those are the only 2 things I can think of, though the 2nd solution is a bit unlikely to be a problem.

**Comment by Enviouse** [comment]
Thanks for the help so far still a no go files are in same extracted folder like I said everything works great except catching of those Pokemon n like k said I have 186 pokeballs so I doubt that can be the problem

**Comment by Enviouse** [comment]
Dw I just restarted it got rid off all my great balls and made sure my items can hold 200 pokeballs I started n it's going great thanks for the help not sure what it was but its working

**Comment by CaptainArghh** [comment]
Alright glad it's fixed :)

**Comment by pokemonloverx333** [comment]
they are bots , there are always small errors , and mostly simple restart solves much , sometimes inventory runs full and it doenst waste items , just restart and it will drop the shit again

**Comment by futi666** [comment]
just restart the bot and wait a few minutes ;)
