### ISSUE TITLE
Strange Issue

### ISSUE THREAD

**Issue by UknownAX** [finndev/PokeBuddy#509]
[P - 13:40:33] [Recycling Items] Recycled: ItemGreatBall x 1
[P - 13:40:33] [Catch Pokemon] Tentacruel got away using a ItemPokeBall, status: CatchError
[P - 13:40:34] [UI] Updating...
[P - 13:40:36] [Catch Pokemon] Encounter failed: EncounterError (can't catch Pokemon)
[P - 13:40:41] [Catch Pokemon] Catching a lured pokemon...
[P - 13:40:42] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 13:40:42] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 13:40:43] [Catch Pokemon] Found: 2 catchable Pokemon
[P - 13:40:44] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 13:40:44] [Catch Pokemon - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 13:40:45] [Catch Pokemon] Catching a lured pokemon...
[P - 13:40:45] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 13:40:45] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 13:40:45] Stopping...

----

**What happened?**

**Comment by UknownAX** [comment]
Just to let you know... I disabled Firewall from Windows and Windows Defender plus I dont have an anti-virus and the program worked again like a charm.

So maybe that was the problem.

**Comment by Deuxgod** [comment]
Servers are unstable

**Comment by UknownAX** [comment]
I noticed... Several Catch Error in 10 minutes...

**Comment by curtiola** [comment]
Catcherror is likely due to being out of pokeballs, bot won't use great or ultra

**Comment by UknownAX** [comment]
I have more than 100 Pokeballs... so thats not the catch error in this case.

**Comment by curtiola** [comment]
The pokeball number by the map includes great and ultra balls, click the small switch on the bottom left corner to see the extended tabs and check individual numbers on the left

**Comment by UknownAX** [comment]
146 Pokeballs bro... Told you, thats not the error in this case, strange.

**Comment by curtiola** [comment]
Ok, not sure what it's about then

**Comment by UknownAX** [comment]
Yep... strange.

**Comment by Sartorius1997** [comment]
Happening to me as well just started last night
