### ISSUE TITLE
[Farm Pokestops - ERROR]: System.UriFormatException: Invalid URI: The hostname could not be parsed

### ISSUE THREAD

**Issue by yccccbb** [finndev/PokeBuddy#520]
Hi,guys,i used this bot last night and it runs good in the first hour so i went to sleep.
When i woke up today,my bot does not work and show me this problem.
Should i change some setting?
Appreciate your help.
--------------------------------------------------
[Farm Pokestops - ERROR]: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.Net.Http.HttpClient.CreateUri(String uri)
   at f$_T6Mr_W\[y-FC->#WFrbxcb#.Ne>C`>$|GL%p?lNqy\*w"\[7_<-`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at f$_T6Mr_W\[y-FC->#WFrbxcb#.PWj4g;\*58KiB#up\\%Bl0WA!@\&`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ;MWzYZd<1PwFW-#dcT<NAO#U".`ekcN9cer!-YoZSZYqg(1x{c"`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ;MWzYZd<1PwFW-#dcT<NAO#U".\*9Eh4`"JmNnq0/_l-4R{:-Ob"`6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at uSC<4V\[z@"caWS'7\,#y6)4?K#.`^4Z\\gVj$-I:!S3i\&1>^BxX7'.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<PopulatePokestops>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by yccccbb** [comment]
have some one met this problem?

**Comment by perfidiousdan** [comment]
Yea just did after 1hour

**Comment by perfidiousdan** [comment]
Then no more pokestop at all

**Comment by yccccbb** [comment]
So what should i change? Walk speed?
