### ISSUE TITLE
is the bot playing up for anyone else

### ISSUE THREAD

**Issue by SamiiJamess** [finndev/PokeBuddy#533]
can anyone please let me know if they are getting things like 
- constantly walking messages
- updating messages
- writing in red colour

**Comment by futi666** [comment]
new pokebuddy update mate



Version: 0.0.7.2
[P - 00:58:09] Info: Settings Window is being improved
[P - 00:58:09] 	 Added: (!) New settings window. Now, everything is configurable.

**Comment by futi666** [comment]
restart it

**Comment by Kokainium** [comment]
Same here

**Comment by elpibeninja** [comment]
servers down guys

**Comment by 2stronkkk** [comment]
RIP BOT?

**Comment by TheUserCB** [comment]
RIP BOT?

**Comment by SamiiJamess** [comment]
i have restarted it loads and i even had a malware issue that avast was blocking me to use the bot

**Comment by Sweg7** [comment]
@2stronkkk r u a dev for Niantic Kappa

**Comment by 2stronkkk** [comment]
ahahahha sure xD

**Comment by Kokainium** [comment]
Working for meget now:)

**Comment by futi666** [comment]
it works normally guys... no worries, just restart the bot and everything works fne, it is just an update!!!!

**Comment by Kokainium** [comment]
Me*

**Comment by 2stronkkk** [comment]
already restart stil no pokestops

**Comment by Kokainium** [comment]
Futi is right

**Comment by Sweg7** [comment]
it wrks 4 me

**Comment by futi666** [comment]
2stronkkk stop trolling the bot works fine ;) just wait 30seconds and the everything works fine!

**Comment by SamiiJamess** [comment]
ok futi thanks guys i thought it was just my end lol

**Comment by SamiiJamess** [comment]
does anyone know an up to date dratini nest

**Comment by Sweg7** [comment]
i found like 5 dratini 40.764550, -73.999411

**Comment by futi666** [comment]
sydney operahouse samii

**Comment by futi666** [comment]
-33.8567844
151.215297

**Comment by Sweg7** [comment]
@SamiiJamess just look at http://pkmngotrading.com/wiki/Nests

**Comment by SamiiJamess** [comment]
i did and none pop up and do i put the walking speed on 0 for it to work

**Comment by curtiola** [comment]
Server issues it seems, lots of people having login problems and missing pokestops and such, even on mobile

**Comment by curtiola** [comment]
Or you just mean dratini doesn't pop up? Lol

**Comment by SamiiJamess** [comment]
yer dratini doesnt pop up do i put the walking speed on 0

**Comment by Sweg7** [comment]
im getting this now 
[P - 19:23:27] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:23:28] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:23:30] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:24:33] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:24:34] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:24:37] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:24:39] [UI] Updating...
[P - 19:24:40] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:24:40] [Farm Pokestops - ERROR]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at cN%\[9PhPw5<g^KqE6siG3Asa.o)a6g"\*'{-9fe~wfXbPt8`Y\*!`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at cN%\[9PhPw5<g^KqE6siG3Asa.3GGqpYA\\R{x^{IWi}\*YCTnX$%`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ~<:iTvcai|l1UH\]Ox\[O9VfXS$.oM2O-xGBb4o"I\.E/EP S(}`C%`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ~<:iTvcai|l1UH\]Ox\[O9VfXS$._M!?_}i0R:lVAO;?c\*jVa?C@!`6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at na^C\*6zu:Yt0|Ue<-R}\[};tt.|RBaopg|Av-}Wid@0xuA<eO6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<PopulatePokestops>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 19:24:43] [UI] Updating...
[P - 19:24:46] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc
[P - 19:24:48] Retrying request https://pgorelease.nianticlabs.com/plfe/528/rpc

**Comment by curtiola** [comment]
0 would make you stand still, I don't know where you are but dratini is a rare spawn, if you're at a dratini nest, the nests aren't small but they're not huge either, I couldn't tell you one way or the other

**Comment by curtiola** [comment]
@sweg7 server isn't doing so hot, unstable as fuck it seems

**Comment by SamiiJamess** [comment]
so it is just preserver and just see

**Comment by nielsm123** [comment]
I just keep walking into the sea....
