### ISSUE TITLE
Encounter error? 

### ISSUE THREAD

**Issue by saintv** [finndev/PokeBuddy#545]
It was working awhile ago and when i turned it back on it kept saying encounter error.
![screenshot_1](https://cloud.githubusercontent.com/assets/20824601/17502820/fd9a66ee-5d9f-11e6-9fc9-e025f705703a.png)

**Comment by peeveswozere** [comment]
He also say: [Farm Pokestops] NoResultSet -> Received XP: 0

Full log:

[P - 04:41:21] Attempting to Login...
[P - 04:41:21] Logging in with method: Google as Auth Provider
[P - 04:41:23] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/393
[P - 04:41:30] [UI] Updating...
[P - 04:41:31] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 04:41:31] [Catch Pokemon - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at uAHu0)b?u'h0Ytj)vH <#-3\].X|-\&|k4 MO4Jp\\YzcCNmv^x;!.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at uAHu0)b?u'h0Ytj)vH <#-3\].#%W3sVkYTB2WM;E<5vq"^4HI".MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by saintv** [comment]
Recycling option doesn't work. Should i just try to download the bot again?

**Comment by peeveswozere** [comment]
Updating to latest version havent changed a thing for me

**Comment by blackbeardbravo** [comment]
rebooting machine did nothing either

**Comment by saintv** [comment]
I just saw that it was updated a few minutes ago and restarted the program and the features are working fine but i still get catch error.

**Comment by blackbeardbravo** [comment]
do you have 'transfer bad pokemon'? I unchecked it and it is now working fine

**Comment by saintv** [comment]
Yeah i been having it, it just started working after restarting.

**Comment by blackbeardbravo** [comment]
my bad. it does not help. still get error

**Comment by curtiola** [comment]
It could be server related, it's been choppy today 
http://cmmcd.com/PokemonGo/

**Comment by blackbeardbravo** [comment]
actually, this started after pokebuddy update.

**Comment by saintv** [comment]
yeah ^

**Comment by finndev** [comment]
fixed

**Comment by Sartorius1997** [comment]
I'm still getting this error
