### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by TeemoOnShrooms** [finndev/PokeBuddy#559]
Here you are

[P - 06:15:56] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

Colour red :dancers:

**Comment by horseyMEAT** [comment]
Me too, same.

**Comment by horseyMEAT** [comment]
Pretty sure that just a softban.

**Comment by TeemoOnShrooms** [comment]
i'm pretty sure it isnt; it keep doing things, catching and whatever, but it just shows that error.

**Comment by joejoejoey04** [comment]
#561

**Comment by TeemoOnShrooms** [comment]
the issue didnt fix, still running... isnt a soft ban cuz anyway it does everything planned.

**Comment by TeemoOnShrooms** [comment]
fixed myself.

**Comment by Sid733** [comment]
how u fixed it?

**Comment by TeemoOnShrooms** [comment]
Put Recycle Items after "reinstalling" pokebuddy from a new download
