### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by pipezierra** [finndev/PokeBuddy#561]
[P - 23:34:55] [Farm Pokestops] InCooldownPeriod -> Received XP: 0
[P - 23:34:55] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by TFSho** [comment]
Yup, me too.
Just created a new account with my spam email. It LOOKS like it is still getting the items, but not sure.

**Comment by Dunkeru** [comment]
That happened to me when my inventory is full try to recycle items and see if the error banish

**Comment by Dunkeru** [comment]
I have the same error

**Comment by horseyMEAT** [comment]
Me too, just start a few minutes ago. Was working great before that.

**Comment by joejoejoey04** [comment]
Not sure what the error spam is, but it's caused by the fact you are softbanned and aren't spinning the pokestops properly. Goes away after a couple of minutes.

**Comment by horseyMEAT** [comment]
So leave it running till it unbans? Or do the spin unban manually then come back to bot?
Thanks.

**Comment by joejoejoey04** [comment]
Mine fixed itself after a few minutes. Just keep an eye on it until you start getting the 50xp rolls from the stops

**Comment by horseyMEAT** [comment]
It fixed it about 20 seconds. Thanks for info.

**Comment by TheColher** [comment]
i have this error but i dont think i'm soft banned
i still can get the pokemons and sometimes there's no error when trying to pickup the pokestops
(sorry for the bad grammar)

**Comment by chichigoodboy** [comment]
Still have this error.

**Comment by TFSho** [comment]
I wonder if it has anything to do with the update. When PoGo got updated last night, there was a feature that supposedly gives you a prompt making sure you are not driving when moving over 50ish mph. I realized that when I was moving short distances at 75 kph, it would be fine, but if I went a long distance to a stop, I would get the Unhandled exception

**Comment by jayhao2000** [comment]
maybe just put your speed under 50km/h will work?

**Comment by lol998** [comment]
maybe it gives you that error if your item storage is full not sure tho

**Comment by Senniet** [comment]
For me it also was the item storage that was full.

**Comment by lol998** [comment]
[P - 02:36:36] [Farm Pokestops] InventoryFull -> Received XP: 50
[P - 02:36:36] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by lol998** [comment]
also it seems to keep spamming the same one over and over for a few seconds and then moves on, since bag is full it keeps spamming and then moves after a few seconds, you need to make it so it doesn't do it more than once if bag is full, also just have it say inventory full without spamming red text.

**Comment by TeemoOnShrooms** [comment]
Had the same Error, fixed #577
