### ISSUE TITLE
Pokestop error

### ISSUE THREAD

**Issue by TheColher** [finndev/PokeBuddy#563]
[P - 03:15:01] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by joejoejoey04** [comment]
#561
