### ISSUE TITLE
No, I am not soft banned, why is this happening?

### ISSUE THREAD

**Issue by rowan777** [finndev/PokeBuddy#566]
[P - 17:21:21] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
etcetc

was working perfectly fine before this update.

why.

**Comment by 404unknown** [comment]
restarting the bot should do the work

**Comment by rowan777** [comment]
just figured it out on my own. for all others having this issue, it occurs when you try to visit a pokestop with a full inventory.

**Comment by botisthebest** [comment]
yes sure, i just tried....
