### ISSUE TITLE
farm pokestops doesnt work

### ISSUE THREAD

**Issue by psblackz** [finndev/PokeBuddy#571]
Just apear that block of red phrases... dont farm any pokestop

**Comment by MrLeonardo** [comment]
[P - 09:56:20] [Farm Pokestops] InCooldownPeriod -> Received XP: 0
This is the error:

[P - 09:56:20] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by Giammaofwar** [comment]
me too

**Comment by TeemoOnShrooms** [comment]
Seems same as mine, but mine did farm and whatever else normally... anyway i fixed putting Recycle Items

**Comment by pokeBuddyUser** [comment]
I am facing the same...

**Comment by psblackz** [comment]
work some times, in 20 errors works one.

**Comment by TeemoOnShrooms** [comment]
Tried to put recycle items?
