### ISSUE TITLE
Bot issues?

### ISSUE THREAD

**Issue by kevmuffin** [finndev/PokeBuddy#573]
I'm stucked in this but on my phone it works
P - 10:00:27] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/389
[P - 10:00:28] [Catch Pokemon] No Pokemon nearby
[P - 10:00:30] [Navigation] Walking from: 37.77, -122.47179 to: 37.7702, -122.47159 with a distance of: 18 meters
[P - 10:00:36] [Navigation] Walking from: 37.77005, -122.47174 to: 37.77025, -122.47154 with a distance of: 18 meters
[P - 10:00:42] [Navigation] Walking from: 37.77009, -122.4717 to: 37.77029, -122.4715 with a distance of: 18 meters
[P - 10:00:48] [Navigation] Walking from: 37.77014, -122.47165 to: 37.77034, -122.47145 with a distance of: 18 meters
[P - 10:00:54] [Navigation] Walking from: 37.77019, -122.4716 to: 37.77039, -122.4714 with a distance of: 18 meters
[P - 10:01:00] [Navigation] Walking from: 37.77027, -122.47152 to: 37.77047, -122.47132 with a distance of: 18 meters
[P - 10:01:06] [Navigation] Walking from: 37.77032, -122.47148 to: 37.77052, -122.47128 with a distance of: 18 meters
[P - 10:01:12] [Navigation] Walking from: 37.77036, -122.47143 to: 37.77056, -122.47123 with a distance of: 18 meters
[P - 10:01:18] [Navigation] Walking from: 37.77041, -122.47138 to: 37.77061, -122.47118 with a distance of: 18 meters
[P - 10:01:24] [Navigation] Walking from: 37.77045, -122.47134 to: 37.77065, -122.47114 with a distance of: 18 meters
[P - 10:01:30] [Navigation] Walking from: 37.7705, -122.47129 to: 37.7707, -122.47109 with a distance of: 18 meters

**Comment by pokeBuddyUser** [comment]
I faced the same issues. But on removing proxy it started working.

But now I am facing a new error. After a few successful spinning of farm pokestops... i started getting following error msgs.

[P - 13:38:39] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by TeemoOnShrooms** [comment]
Same as mine :) fixed tho

**Comment by kevmuffin** [comment]
@pokeBuddyUser that happens when you're going to pokestops with a full inventory

**Comment by LuciiSky** [comment]
Guys if it stops farming pokestops and hasnt repopulated close it reopen it and start it without farming pokestops activated then when your account has fully loaded activate farm pokestops and it should repopulate them works for me every time
