### ISSUE TITLE
Bot keeps write red program error to log 

### ISSUE THREAD

**Issue by fabech** [finndev/PokeBuddy#577]
[P - 11:10:18] PokeBuddy launching...
[P - 11:10:18] Version: 0.0.7.7
[P - 11:10:18] Info: Settings Window is being improved
[P - 11:10:18] 	 Added: (!) New settings window. Now, everything is configurable.
[P - 11:10:18] 	 Fixed: Bot now uses all available pokeballs again.
[P - 11:10:18] 	 Fixed: Start/Stop button responsability.
[P - 11:10:18] 	 Fixed: The UI now resets after stopping the bot.
[P - 11:10:18] 	 New feature: Added Minimize Button.
[P - 11:10:18] 	 New feature: Log color depending on event.
[P - 11:10:18] This bot is free to use. If you paid for it, you got scammed.
[P - 11:10:18] Feel free to donate to (PayPal): support@epicdevs.de (make sure to email me afterwards)
[P - 11:10:18] --------------------------------
[P - 11:10:37] Attempting to Login...
[P - 11:10:37] Logging in with method: Google as Auth Provider
[P - 11:10:40] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/352
[P - 11:10:40] [Recycling Items] Recycling: 5 items
[P - 11:10:41] [Recycling Items] Recycled: ItemPokeBall x 1
[P - 11:10:41] [Catch Pokemon] Found: 3 catchable Pokemon
[P - 11:10:42] [Catch Pokemon] Psyduck got away using a ItemPokeBall, status: CatchFlee
[P - 11:10:43] [Recycling Items] Recycled: ItemPotion x 16
[P - 11:10:43] [Transferring Pokemons] Transferring Pokemon away: Metapod (CP: 27)!
[P - 11:10:43] [Transferring Pokemons] Metapod has been transferred
[P - 11:10:44] [Recycling Items] Recycled: ItemSuperPotion x 5
[P - 11:10:45] [Recycling Items] Recycled: ItemHyperPotion x 3
[P - 11:10:46] [Catch Pokemon] Magikarp got away using a ItemPokeBall, status: CatchFlee
[P - 11:10:47] [Recycling Items] Recycled: ItemRevive x 20
[P - 11:10:48] [Transferring Pokemons] Transferring Pokemon away: Pidgey (CP: 202)!
[P - 11:10:49] [Transferring Pokemons] Pidgey has been transferred
[P - 11:10:50] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 11:10:51] [Catch Pokemon] Berry has been successfully used
[P - 11:10:51] [Catch Pokemon] Goldeen got away using a ItemPokeBall, status: CatchFlee
[P - 11:10:54] [Transferring Pokemons] Transferring Pokemon away: Spearow (CP: 324)!
[P - 11:10:54] [Recycling Items] There are no items to recycle
[P - 11:10:54] [Transferring Pokemons] Spearow has been transferred
[P - 11:10:56] [Farm Pokestops] Populated Pokestops
[P - 11:10:57] [Catch Pokemon] Catching a lured pokemon...
[P - 11:10:57] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 11:10:57] [Catch Pokemon] Berry has been successfully used
[P - 11:10:57] [Catch Pokemon] Bulbasaur got away using a ItemPokeBall, status: CatchFlee
[P - 11:10:58] [Navigation] Walking from: 51.5076, -0.12782 to: 51.50778, -0.12794 with a distance of: 13 meters
[P - 11:10:59] [Farm Pokestops] Spinning Pokestop: 'Nelson's Column'
[P - 11:10:59] [Recycling Items] There are no items to recycle
[P - 11:10:59] [Farm Pokestops] Success -> Received XP: 0
**[P - 11:10:59] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()**
[P - 11:10:59] [Transferring Pokemons] Transferring Pokemon away: Spearow (CP: 170)!
[P - 11:11:00] [Transferring Pokemons] Spearow has been transferred
[P - 11:11:00] [Catch Pokemon] No Pokemon nearby
[P - 11:11:02] [Catch Pokemon] Encounter failed: EncounterAlreadyFinished (can't catch Pokemon)
[P - 11:11:02] [Navigation] Walking from: 51.50764, -0.12784 to: 51.50778, -0.12794 with a distance of: 11 meters
[P - 11:11:03] [Farm Pokestops] Spinning Pokestop: 'Nelson's Column'
[P - 11:11:04] [Farm Pokestops] Success -> Received XP: 0
**[P - 11:11:04] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()**
[P - 11:11:04] [Recycling Items] There are no items to recycle
[P - 11:11:05] [Transferring Pokemons] Transferring Pokemon away: Spearow (CP: 10)!
[P - 11:11:05] [Transferring Pokemons] Spearow has been transferred
[P - 11:11:05] [Catch Pokemon] No Pokemon nearby
[P - 11:11:07] [Catch Pokemon] Encounter failed: EncounterAlreadyFinished (can't catch Pokemon)
[P - 11:11:07] [Navigation] Walking from: 51.50766, -0.12786 to: 51.50778, -0.12794 with a distance of: 9 meters
[P - 11:11:09] [Farm Pokestops] Spinning Pokestop: 'Nelson's Column'
[P - 11:11:09] [Farm Pokestops] Success -> Received XP: 0
**[P - 11:11:09] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()**
[P - 11:11:10] [Recycling Items] There are no items to recycle
[P - 11:11:10] [Transferring Pokemons] Transferring Pokemon away: NidoranFemale (CP: 424)!
[P - 11:11:10] Stopping...
[P - 11:11:11] [Transferring Pokemons] NidoranFemale has been transferred
[P - 11:11:11] [Catch Pokemon] No Pokemon nearby
[P - 11:11:13] [Catch Pokemon] Encounter failed: EncounterAlreadyFinished (can't catch Pokemon)
[P - 11:11:13] [Navigation] Walking from: 51.50769, -0.12788 to: 51.50778, -0.12794 with a distance of: 7 meters
[P - 11:11:14] [Farm Pokestops] Spinning Pokestop: 'Nelson's Column'
[P - 11:11:14] [Farm Pokestops] Success -> Received XP: 0
**[P - 11:11:14] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()**
[P - 11:11:16] [Transferring Pokemons] Transferring Pokemon away: Clefairy (CP: 47)!
[P - 11:11:16] [Transferring Pokemons] Clefairy has been transferred
[P - 11:11:21] [Transferring Pokemons] Transferring Pokemon away: Zubat (CP: 23)!
[P - 11:11:22] [Transferring Pokemons] Zubat has been transferred
[P - 11:11:27] [Transferring Pokemons] Transferring Pokemon away: Psyduck (CP: 269)!
[P - 11:11:27] [Transferring Pokemons] Psyduck has been transferred

**Comment by JCortexs** [comment]
i have the same problem, usually it works but after 10 min it appears this error:
[P - 11:14:12] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by TeemoOnShrooms** [comment]
Same as what happened to me, try those:
- Set and put Recycle Items
- If doesnt work, delete folders and "reinstall", then put Recycle Items

**Comment by JCortexs** [comment]
it worked for you?

**Comment by TeemoOnShrooms** [comment]
Sure -.-" why i'm suggesting that?

**Comment by PromethiumFire** [comment]
Your receiving 0 XP from stops. This means you have been soft banned and basically the red writing is telling you that. Leave your bot running for a little while until your soft ban is lifted and everything will be fine.

**Comment by fabech** [comment]
I have enabled the downloaded new bot folder, and enabled Recycle Items, doesnt work.

**Comment by TeemoOnShrooms** [comment]
Nah, i wasnt soft banned and the only way to fix it was to do what i wrote above...

**Comment by fabech** [comment]
I'm softbanned.. :-D

**Comment by TeemoOnShrooms** [comment]
Unlucky then

**Comment by JCortexs** [comment]
this error only happens in 2 of my 3 acounts ;S;S WHY!!! ?¿?¿ =)

**Comment by TeemoOnShrooms** [comment]
I fixed like i said, happened to me too on only one account.

**Comment by TeemoOnShrooms** [comment]
anyway, did you set the items section before putting Recycle Item? i had to set it up correctly before fixing.

**Comment by JCortexs** [comment]
i deleted all files , downloaded new zip and it dosent work ;S;S;S

**Comment by fabech** [comment]
Its because of softban :)

**Comment by JCortexs** [comment]
but in 2 of my 3 acounts? and i just jump 2km

**Comment by TeemoOnShrooms** [comment]
Mhh, set up items maybe? trying to change something, like 0 potion, superpotion, ... i did like that and fixed this morning... and no I WASN'T SOFTBANNED

**Comment by JCortexs** [comment]
just have revive to 0, change it to 5 and dosent work ;S

**Comment by TeemoOnShrooms** [comment]
it's the opposite... try to put revive 0, potions 0 and super pots 0, pokeball 15

**Comment by Sartorius1997** [comment]
It was doing the same to me but it just sorted itself out. I wasn't softbanned. Just ran it until it stopped

**Comment by Noodlezs** [comment]
clearing out Items worked for me, setting common items like revives, potions and super potions to zero also helped, retaining hyper (40) & max (40) potions with low (40) pokeballs, mid great balls (80) and high (100) ultra balls, leaving space for farming to run ok

**Comment by TheColher** [comment]
Worked for me
thx TeemoOnShrooms
