### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ukyo28** [finndev/PokeBuddy#578]
[P - 12:13:40] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 12:13:41] [Catch Pokemon] No Pokemon nearby
[P - 12:13:42] [Recycling Items] There are no items to recycle
[P - 12:13:43] [Navigation] Walking from: 41.89197, 12.47404 to: 41.89202, 12.47381 with a distance of: 12 meters
[P - 12:13:44] [Farm Pokestops] Spinning Pokestop: 'Dipinti Ottocenteschi'
[P - 12:13:45] [Farm Pokestops] InCooldownPeriod -> Received XP: 0
[P - 12:13:45] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

What is that?

**Comment by TeemoOnShrooms** [comment]
Watch previous posts.
