### ISSUE TITLE
Bot Stuck?

### ISSUE THREAD

**Issue by rmarquez5** [finndev/PokeBuddy#588]
Downloaded the newest archive from the master directory. Keep getting this error as the bot tries to travel from the first pokestop it finds to the next one.

[P - 05:46:27] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by RayTwente** [comment]
I have no problem to the bot now been running for 12 hours

Yesterday I had that too
but that was because of updated .Niantic

**Comment by Thorben24** [comment]
Did you try teleport to the next pokestop, if yes, turn it of. If not, turn it on (just for a test)? Also disable your antivirus and restart the bot.

**Comment by RayTwente** [comment]
as you move from one place to another which no valid travel time does 

dan, you have a soft ban

**Comment by RayTwente** [comment]
I discovered yesterday
further're like an egg to hatch
continue to run 12 km
.Niantic have admitted update adds

**Comment by rmarquez5** [comment]
The error started happened when i downloaded the newest version of the bot this morning. I'm not teleporting. I've set it to walk 10 km/hr only. There is no indication of a soft ban because it farms the farms the first pokestop, catches pokemon at that pokestop, and then tries to move to the next one and throws the error. 

I'm not at my computer now, but I'll try again tonight. I won't close this issue until I see someone else find a resolution to it, if its an issue at all.

**Comment by rmarquez5** [comment]
So I'm reading some other posts about a similar issue and a suggestion is to clear out a little inventory so that its not at or over the max 350 items. I'll try that and restart the bot when I get home if I don't get it going sooner.

**Comment by RayTwente** [comment]
That's right if too many items do you get those error messages
cleanup faste: hihi


isseu  can be concluded is fixed it
