### ISSUE TITLE
Can someone solve this??

### ISSUE THREAD

**Issue by kaliorang** [finndev/PokeBuddy#589]
Hi, when i am botting, sometimes (often) appear this text colored with red.

[P - 12:59:06] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

?? Can someone tell me, whats the problem??

**Comment by futi666** [comment]
close the bot an restart it, its an update mate

**Comment by Ceepax** [comment]
also try to make some space in your inventory, fixed it for me

**Comment by KHAMELEON1992** [comment]
restarting isnt working for me? and this is brand new account so its got no items

**Comment by KHAMELEON1992** [comment]
it was the inventory...i had leveled up loads and when i logged in on my phone i got loads of items

**Comment by Rab89** [comment]
yep i recycled items and it worked

**Comment by Noodlezs** [comment]
clearing out Items worked for me, setting common items like revives, potions and super potions to zero also helped, retaining hyper (40) & max (40) potions with low (40) pokeballs, mid great balls (80) and high (100) ultra balls, leaving space for farming to run ok
