### ISSUE TITLE
why error? (Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements)

### ISSUE THREAD

**Issue by krll-k** [finndev/PokeBuddy#590]
`[P - 14:08:39] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()`

**Comment by futi666** [comment]
close the bot an restart it, its an update mate

**Comment by KHAMELEON1992** [comment]
i have the same issue and it wont go with just a restart

**Comment by KHAMELEON1992** [comment]
whenever it trys to farm a pokestop i get this ' [P - 12:19:37] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()'

**Comment by Ceepax** [comment]
Make some space in your inventory, fixed it for me

**Comment by futi666** [comment]
close the bot an restart it, its an update mate

**Comment by BraianNunes** [comment]
Hello. Same here. I've restarted many times but no success :(

**Comment by Lynomm** [comment]
Same.

**Comment by Hypersonicx** [comment]
> Ceepax - Make some space in your inventory, fixed it for me

You have to do it manually with your smartphone and your fingers. This will fix it
