### ISSUE TITLE
New Issue Please Help

### ISSUE THREAD

**Issue by brynnie1** [finndev/PokeBuddy#607]
This is what i get: Please Help : 

[P - 13:53:29] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by Rab89** [comment]
Can you read??

**Comment by KillerSpecht** [comment]
1. restart the Bot
or
1. delete the Pokebuddy-folder and re download

**Comment by brynnie1** [comment]
ye done that but still having same issue

**Comment by SamiiJamess** [comment]
you are probably have a soft ban
