### ISSUE TITLE
PokeBuddy Won't Launch

### ISSUE THREAD

**Issue by TheWonderSpud** [finndev/PokeBuddy#621]
I get this error when I try to run the PokeBuddy EXE. Windows Firewall is disabled. I have all permissions. I have disabled my AV. Why am I getting this error? I live miles away from pokestops and I can't play the game until I get PokeBuddy to work.

""Unexpected error during update routine!

Routine: ","
Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\Alex\Documents\%PGOBot\PokeBuddy-master(3)\PokeBuddy-master\PokeBuddy\Core\PokeBuddy.Core.dll' is denied.
at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 buffersize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
at (htap gnirtS).
at .(sgra 2'yranoitciD ,iu wodniWtadpU)
at PokeBuddy.Views.UpdateWindow.)sgra tcejbO(""

**Comment by Krome333** [comment]
Delete and Réinstall it !

**Comment by curtiola** [comment]
This looks like a permissions problem accessing core.dll
I remember suggesting many different things that didn't work for you lol but it says access denied so it's almost definitely not any firewall, but probably some missing permission somewhere, pc won't say access denied if you have the permission to access it
