### ISSUE TITLE
BOt having UI and Catch errors

### ISSUE THREAD

**Issue by masterblasterking** [finndev/PokeBuddy#622]
![pokebuddyissue](https://cloud.githubusercontent.com/assets/20930982/17523179/b2167edc-5e27-11e6-9580-2249003d8d7f.png)

So my bot will not add my level, or the pokeballs to the ui. It also has been giving me this error for the passed 4 hours now when I connect. I have 103 pokeballs so I dont know whats going on. Movement speed is set to 10kms and the elevation is at 10. No berry's selected to be used.

[P - 11:45:16] Attempting to Login...
[P - 11:45:16] Logging in with method: Google as Auth Provider
[P - 11:45:16] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/385
[P - 11:46:16] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 11:46:17] [Catch Pokemon - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at -KF=YmSiDj\]cx#A{_wLBUV%i$.<EkHZQ\&@e3\,\*?zz6jl$\&;hvi).MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at -KF=YmSiDj\]cx#A{_wLBUV%i$.t~%v79XM<k\[5%1`TaQ9bsdX!(.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by Jose009** [comment]
Same error, waiting....

**Comment by vendunk** [comment]
Looks like a soft ban

**Comment by masterblasterking** [comment]
Its not a sb. Im playing normally. Testing it around my actual locationn to
test it.

**Comment by TeemoOnShrooms** [comment]
#582

**Comment by Jose009** [comment]
@TeemoOnShrooms  no work for me
