### ISSUE TITLE
The bot does not catch pokemon.

### ISSUE THREAD

**Issue by TheTomas** [finndev/PokeBuddy#654]
It also doesnt show my level, pokeballs and berries.

here is a error i get.

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 23:20:24] [Catch Pokemon] Catching a lured pokemon...
[P - 23:20:24] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RS)#<UWr_KphqF//E!\]@EdTM".\.)SXvOdEjm@\*}9Q5O-EGXk h.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RS)#<UWr_KphqF//E!\]@EdTM".l/\,MB\\?u)FN24FDy9\&9z"-aK(.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 23:20:25] [Catch Pokemon] Catching a lured pokemon...
[P - 23:20:25] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RS)#<UWr_KphqF//E!\]@EdTM".\.)SXvOdEjm@\*}9Q5O-EGXk h.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RS)#<UWr_KphqF//E!\]@EdTM".l/\,MB\\?u)FN24FDy9\&9z"-aK(.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 23:20:24] [Catch Pokemon] Catching a lured pokemon...
[P - 23:20:24] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RS)#<UWr_KphqF//E!\]@EdTM".\.)SXvOdEjm@\*}9Q5O-EGXk h.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RS)#<UWr_KphqF//E!\]@EdTM".l/\,MB\\?u)FN24FDy9\&9z"-aK(.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 23:20:25] [Catch Pokemon] Catching a lured pokemon...
[P - 23:20:25] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RS)#<UWr_KphqF//E!\]@EdTM".\.)SXvOdEjm@\*}9Q5O-EGXk h.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification..

**Comment by meout** [comment]
I'm experiencing the same issue with the same message. No pokeballs, no berries, and cannot catch pokemon. It also will not show my current level.

**Comment by curtiola** [comment]
2 Others solved this by simply restarting the pc, have you tried?

**Comment by TheTomas** [comment]
Yes! That worked :) i deleted All My folders and restarted My pc, then i downloaded pokebuddy again. Now it is working like it was before.

**Comment by curtiola** [comment]
Perfect
