### ISSUE TITLE
Catching 'lured' pokemon + Idea

### ISSUE THREAD

**Issue by DJ-Xero** [finndev/PokeBuddy#699]
I got the following crash data for you guys..

[P - 09:19:41] [Catch Pokemon] Catching a lured pokemon...
[P - 09:19:41] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at dwb7:\.\*$/#)|\.XWp_|VK}\.^n$.RnfK|\]re^\.!qA1w%r;cFze'\]$.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dwb7:\.\*$/#)|\.XWp_|VK}\.^n$.f/KXD`P^<M`(L\\%-Pvf{EI>K'.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 09:19:42] [Catch Pokemon] Catching a lured pokemon...
[P - 09:19:42] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.

Hope you can fix this, thanx in advanced.

Btw... Can you implement a option for using proxys?
This would be a nice feature ! :dancers:

**Comment by Thorben24** [comment]
The error can be fixed easily by doing this:
#582 
"Stop the bot, set up the item section correctly, restart the bot
or
Stop the bot, close, delete all folders, re-extract and set up correctly the item section (changing values), restart and Enjoy"

I actually use the software: Proxifier (https://www.proxifier.com/) for this.

You can tunnel every PokeBuddy instance / process with an own proxy.
