### ISSUE TITLE
In Depth Guide For Pokebuddy's Most Common Issues

### ISSUE THREAD

**Issue by DatFIXER** [finndev/PokeBuddy#863]
_**IN DEPTH GUIDE ON POKEBUDDY ISSUES_

SOFT-BAN - How do i recognize if i'm being softbanned?**

Pokestops usually give 0 exp, the bot runs but can't catch pokemons or farm pokestops.

**How can i prevent softbans?**

-Keep an eye on coordinates and times to avoid jumping for Ex from NYC to Sidney
-If you can log in to the phone without GPS activated and while the bot is stopped (Check out is stopped completely, or simply close it)

**HOW DO I FIX THIS?**

- Stop the bot and close
- Open the bot
- Mark ONLY Farm Pokestops
- Let him run for 10-12 minutes

**IP-BAN - How do i recognize if i'm being IPbanned?**

The bot or the phone doesn't load Pokestops, Gyms and he keep moving (usually) from A to B doing nothing.

**How can i prevent IPbans?**

-Run one account only
-Make sure the Hatching Eggs new feature isn't marked (for now causes this issues, waiting for a fix)
-Don't run too fast (i use to walk below 15 km/ph, try higher at your own risk)
-Don't switch too fast from one account botting to another one

**How do i fix IPbans?**

-You can try to restart your router/modem/Whatever
-Keep Hatching Eggs disabled (You can always stop the bot, login to phone with GPS OFF, set the incubators, restart the bot)
-You can try to use a VPN or some software/in browser app that changes IP (even if for me works pretty fine without any of those)

**TRANSFERRING WANTED POKEMONS**

I usually prevent this:
- Loggin in to my phone whenever i see he catches/hatches a pokemon i want to keep, GPS OFF, BOT STOPPED
- Mark it as favourite (Star)
- Restart the bot

Waiting for a fix on that issue

**POKEBUDDY MISSES A LOT WHEN CATCHING POKEMONS**

I usually prevent this:
- Set up -> Items -> Use Berry -> Change the value there, he should catch often and more probably

Hope those helps :+1:  Have Fun!

**Comment by hendroxy** [comment]
#858

**Comment by Kielan89** [comment]
Thank you.

**Comment by rymmywife** [comment]
i live in st catharines, the city near Toronto. i set my bot in Toronto and i get ip banned in 3mins, i have tried to use VPN but it didn't work, i got ip banned in 30mins when i set in NY before. Please help me.

**Comment by matt2310** [comment]
@DatFIXER  how are you marking it as favorite by hitting the star when gps is off because the little red box that says gps signal not found covers where the star is and you cant click it

**Comment by fabiosb01** [comment]
what about this error?
**[Error] GoogleAuthError: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing.**
i've seen a lot of people asking about this.. wish someone could help... #841

**Comment by rmarquez5** [comment]
@matt2310 Go to the button in the lower right-hand corner. you can both transfer and favorite your pokes there.

**Comment by matt2310** [comment]
@rmarquez5  you the real M.V.P.

**Comment by rymmywife** [comment]
![image](https://cloud.githubusercontent.com/assets/20826953/17597706/1deccf78-5fc5-11e6-93d4-479b48cdf90d.png)
LIKE THIS..

**Comment by sacronor** [comment]
[Error] GoogleAuthError: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing.
google autentification for suspicious activity, Pobably because a VPN service to change logation.
Sing in in ur google account and it will advice you about that activity, check that it was you and it is solved.

**Comment by DatFIXER** [comment]
@rymmywife IP BAN probably

**Comment by fabiosb01** [comment]
@sacronor already sign in on my google account but nothing happens. nothing about any activity :'(

**Comment by DatFIXER** [comment]
I was logged and it worked fine, can't say if it's a new issue tho cuz i stopped about 20min ago.
So if no one has it working, i suggest to don't login till we understand if could be an attempt to ban by Niantics (i remember finndev stopping the log of pokebuddy, when the unknown6 came out, to prevent bans).

**Comment by RedSalsicha** [comment]
Server OFF: http://www.mmoserverstatus.com/pokemon_go

**Comment by fabiosb01** [comment]
@DatFIXER do you have something to tell about my problem dude? i dont know what to do anymore... i'm losing the hope

**Comment by DatFIXER** [comment]
@fabiosb01 have you already tried a fresh installation?

**Comment by fabiosb01** [comment]
@DatFIXER i have no idea how to do that, but i've tried everything about google account and it didnt works. i'm sorry, english isnt my language...

**Comment by fabiosb01** [comment]
since this error appeared, i haven't tried delete all folders and download bot again cuz i believe the bot isn't the problem but google account...

**Comment by DatFIXER** [comment]
Are you italian? (i'm :dancers: )
You can try a fresh installation as you said: delete all folders, re-extract pokebuddy and see if it goes (Incubators OFF obiouvsly)

**Comment by fabiosb01** [comment]
i'm brazilian hah, but my grandfather was italian XD
i'll try it when i get home... thanks in advance man !

**Comment by sacronor** [comment]
close google account in all devices and restart you pc , the message has to appear. its automatic in my case them u ar asked to prove it is you and show a menu, 1st is to send a mensage to ur phone to answer if it was you or not.

**Comment by DatFIXER** [comment]
No problem bro, i can understand spanish but can't talk XD! i'm sorry :+1:

**Comment by fabiosb01** [comment]
but we speak portuguese :O
thanks @sacronor i'll try this too

**Comment by sacronor** [comment]
im brazilian too XD

**Comment by fabiosb01** [comment]
ta me tirando cara, eu extraindo todo meu conhecimento em inglês e vc me vem com essa hahahah

**Comment by sacronor** [comment]
aqui se fala ingles cara :P

**Comment by fabiosb01** [comment]
sorry :+1: hope your suggestion works... cya !

**Comment by T2HotZero** [comment]
@DatFIXER Alright so the program works fine for about a few minutes and then stops working all together. Like I mentioned in another form I went through all the fixs and it doesn't work. Should I be using a fake GPS or something? All I can think is since it happens and then goes away after an hour or more it must be a ban. I am on my computer using the pokebuddy, does that matter? Like I said I put every setting as you suggested. Any suggestions or help I would appreciate.

**Comment by DatFIXER** [comment]
Well seems a IP BAN, but first: are you using EU coordinates? cuz servers in EU are down.

**Comment by T2HotZero** [comment]
How are they IP banning me with the setting you suggested? Should I not be using my computer or something? Yeah I am from the US... Using Central Park

**Comment by T2HotZero** [comment]
Also it literally worked for about 3min

**Comment by DatFIXER** [comment]
I'm thinking man, isn't easy to figure out, trying to.

Did you jump from X to Y?

**Comment by T2HotZero** [comment]
LOL, i know u are doing ur best. Nope I just press go and leave it alone.

**Comment by DatFIXER** [comment]
But before pressing Go, have you logged on phone GPS ON, or were you into another location?
(sorry for the many questions, but i need to know xD!)

**Comment by T2HotZero** [comment]
Wait.... I have to do something with my cell phone?! I thought only needed to use my computer. Also last night it worked for about 2hrs haha

**Comment by T2HotZero** [comment]
I downloaded the application on my computer and run PokeBuddy from here. I don't touch my cell phone =?

**Comment by DatFIXER** [comment]
no no, you don't have unless you want to, but according with what i say in my post, be sure to avoid jumps with gps :+1: 

So today starting it, it gives this issue right?
Resume me what you did from that moment pls

**Comment by T2HotZero** [comment]
Right, I don't log on my phone unless I finish with the program and I want to battle a gym. Okay so last night I followed a Youtube guide, logged in and set it up. Incubator and all.... So then I felt like switching locations... After I switched locations it all got messed up. So I said poop and tried a different Pokemon Go account. Well, it ran for about 30min and then the location disappeared. So I said I would try it in the AM. This morning it ran, for about 2-3min and BOOM nothing worked, like a soft ban. This has continued every few hours. I downloaded the VPN, which i have no idea if I am using it right, and switch my IP in the command setting prompt. But yeah i keep running into the same issue

**Comment by DatFIXER** [comment]
I use pokebuddy without running any VPN or similar, i just keep an eye to avoid "jumps" with gps.
The soft ban it's just about receiving 0 exp from pokestops and can't catch pkmns, but the bot run normally.
If yours can't run normally and farm with 0 exp is probably an IP ban, and probably due to the fact you switched those 2 accounts (only one should run, and you can't stop the bot and put a new one, you need to wait a lot of time to do that i believe)

**Comment by T2HotZero** [comment]
That was about 16hrs ago though

**Comment by T2HotZero** [comment]
im also at work so there is a new ip address

**Comment by DatFIXER** [comment]
yeah strange
anyway right now Google Aut seems having problems... i'm currently logged so i'll try to see if i get same problem

http://www.mmoserverstatus.com/pokemon_go

**Comment by T2HotZero** [comment]
Do u know the name of the folder i would need to delete in order to clear the pokebuddy app?

**Comment by T2HotZero** [comment]
Larry if you read all my post you would know THOSE STEPS DON'T WORK

**Comment by vicelikedust** [comment]
3 mins in and I'm Ip Banned...Again

**Comment by T2HotZero** [comment]
just like me =)

**Comment by matt2310** [comment]
My Vpn keep getting banned every 3-6 mins

**Comment by DatFIXER** [comment]
I'm checking right now guys.. give me some minutes to see if mine does it too

**Comment by MariaBitterlich** [comment]
@DatFIXER, pretty good summary of all the ban aspects! Today I heard of a WIFI router in a car and all 4 people inside the car playing Pokémon while being driven using their mobile phones and the same WIFI without any problems. He claims, that the WIFI router has a stable external IP and following the IP ban theory, all 4 players should be banned after a while. But that doesn't happen at all...

**Comment by DatFIXER** [comment]
Ok mine it's on 6 minutes and working fine.
Lemme resume mine is:
-1 account
-NYC Central Park
-Speed below 15 km/ph
-Egg Incubators Unchecked
-All checked except Evolve Pkmns
-Not currently using any other bots (like Necrobot today using it with Pkbuddy gave me IP Ban)
-Pkmns and Items not Full

**Comment by MariaBitterlich** [comment]
@DatFIXER, if my theory - that there's no such thing as an IP ban - then your not will run into a ban sooner or later. I think that they can detect after ~30 min out of the behavior whether it's a bot or not. If they detect a bot, than they ban exactly this IP. In that way a lot of people could use the same IP without being banned, but the current bot version can not run for a very long while regardless of IP. If my theory is correct, than we have to look into the behavior of the bot and change it in certain parameters more human-like. What do you think?

**Comment by BoatGravy57** [comment]
When I tried botting. There where no pokestops on the minimap. And it kept saying * no pokemon nearby *

**Comment by DatFIXER** [comment]
@MariaBitterlich i've already suggest to do so, and others before me i think (the humanizer-option, #172 )
My bot is working for 1h18min everything's fine, no bans, no bug

**Comment by DatFIXER** [comment]
You could also try to change a number in the Device Id, maybe could help (file txt)

**Comment by T2HotZero** [comment]
@DatFIXER Trying those exact settings.... Will report back

[P - 17:26:47] PokeBuddy launching...
[P - 17:26:47] Version: 0.0.9.2
[P - 17:26:47] Info: Settings Window is being improved
[P - 17:26:47] 	 Added: (!) New settings window. Now, everything is configurable.
[P - 17:26:47] 	 Fixed: Bot now uses all available pokeballs again.
[P - 17:26:47] 	 Fixed: Start/Stop button responsability.
[P - 17:26:47] 	 Fixed: The UI now resets after stopping the bot.
[P - 17:26:47] 	 New feature: Added Minimize Button.
[P - 17:26:47] 	 New feature: Log color depending on event.
[P - 17:26:47] 	 New feature: The bot now uses Incubators
[P - 17:26:47] This bot is free to use. If you paid for it, you got scammed.
[P - 17:26:47] Feel free to donate to (PayPal): support@epicdevs.de (make sure to email me afterwards)
[P - 17:26:47] --------------------------------
[P - 17:29:05] Attempting to Login...
[P - 17:29:05] Logging in with method: Google as Auth Provider
[P - 17:29:13] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/95
[P - 17:29:14] [Recycling Items] There are no items to recycle
[P - 17:29:16] [Catch Pokemon] No Pokemon nearby
[P - 17:29:18] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 17:29:20] [Recycling Items] There are no items to recycle
[P - 17:29:25] [Recycling Items] There are no items to recycle
[P - 17:29:26] [Farm Pokestops] Populated Pokestops
[P - 17:29:27] [Catch Pokemon] Catching a lured pokemon...
[P - 17:29:28] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 17:29:28] [Catch Pokemon] Berry has been successfully used
[P - 17:29:28] [Catch Pokemon] We caught a Pidgey (Probability: 32.67%) with CP 353, used 1 x ItemPokeBall and received 210 XP
[P - 17:29:29] [Navigation] Walking from: 40.78509, -73.96828 to: 40.78456, -73.96836 with a distance of: 37 meters
[P - 17:29:31] [Recycling Items] There are no items to recycle
[P - 17:29:36] [Farm Pokestops] Spinning Pokestop: 'Large Wooden Shaper Glyph'
[P - 17:29:36] [Recycling Items] There are no items to recycle
[P - 17:29:36] [Farm Pokestops] Success -> Received XP: 50
[P - 17:29:40] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 17:29:41] [Catch Pokemon] We caught a Rattata (Probability: 68.91%) with CP 67, used 1 x ItemPokeBall and received 210 XP
[P - 17:29:41] [Navigation] Walking from: 40.78475, -73.96833 to: 40.78428, -73.96847 with a distance of: 34 meters
[P - 17:29:42] [Recycling Items] There are no items to recycle
[P - 17:29:44] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 17:29:47] [Farm Pokestops] Spinning Pokestop: 'The Abraham and Joseph Spector Playground'
[P - 17:29:47] [Farm Pokestops] Success -> Received XP: 50
[P - 17:29:48] [Recycling Items] Recycling: 2 items
[P - 17:29:48] [Recycling Items] Recycled: ItemPokeBall x 1
[P - 17:29:49] [Catch Pokemon] No Pokemon nearby
[P - 17:29:49] [Recycling Items] Recycled: ItemGreatBall x 2
[P - 17:29:52] [Navigation] Walking from: 40.78445, -73.96842 to: 40.78443, -73.96976 with a distance of: 70 meters
[P - 17:29:56] [Recycling Items] Recycling: 2 items
[P - 17:29:58] [Recycling Items] Recycled: ItemPokeBall x 1
[P - 17:30:00] [Recycling Items] Recycled: ItemGreatBall x 2
[P - 17:30:08] [Recycling Items] There are no items to recycle
[P - 17:30:10] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 17:30:14] [Recycling Items] There are no items to recycle
[P - 17:30:16] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 17:30:17] [Catch Pokemon] We caught a Rattata (Probability: 100%) with CP 10, used 1 x ItemPokeBall and received 210 XP
[P - 17:30:17] [Farm Pokestops] Spinning Pokestop: 'Mariners Gate Central Park'
[P - 17:30:17] [Farm Pokestops] Success -> Received XP: 50
[P - 17:30:19] [Recycling Items] There are no items to recycle
[P - 17:30:21] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 17:30:21] [Catch Pokemon] We caught a NidoranFemale (Probability: 47.34%) with CP 219, used 1 x ItemPokeBall and received 210 XP
[P - 17:30:27] [Catch Pokemon] No Pokemon nearby
[P - 17:30:34] [Farm Pokestops] Populated Pokestops
[P - 17:30:35] [Catch Pokemon] Catching a lured pokemon...
[P - 17:30:35] [Catch Pokemon] We caught a Oddish (Probability: 49.83%) with CP 386, used 1 x ItemPokeBall and received 210 XP
[P - 17:30:35] [Navigation] Walking from: 40.78443, -73.96954 to: 40.78448, -73.97012 with a distance of: 30 meters
[P - 17:30:35] [Transferring Pokemons] Transferring Pokemon away: Rattata (CP: 10)!
[P - 17:30:35] [Transferring Pokemons] Rattata has been transferred
[P - 17:30:39] [Farm Pokestops] Spinning Pokestop: 'Twin Owls'
[P - 17:30:40] [Farm Pokestops] Success -> Received XP: 50
[P - 17:30:40] [Transferring Pokemons] Transferring Pokemon away: NidoranFemale (CP: 219)!
[P - 17:30:41] [Transferring Pokemons] NidoranFemale has been transferred
[P - 17:30:44] [Navigation] Walking from: 40.78446, -73.96986 to: 40.78394, -73.97051 with a distance of: 50 meters
[P - 17:30:44] [Catch Pokemon] No Pokemon nearby
[P - 17:30:57] [Farm Pokestops] Spinning Pokestop: 'Four Greek Gods'
[P - 17:30:58] [Farm Pokestops] Success -> Received XP: 50
[P - 17:31:02] [Catch Pokemon] No Pokemon nearby
[P - 17:31:02] [Navigation] Walking from: 40.78409, -73.97031 to: 40.78371, -73.96977 with a distance of: 39 meters
[P - 17:31:11] [Farm Pokestops] Spinning Pokestop: 'Summit Rock'
[P - 17:31:11] [Farm Pokestops] Success -> Received XP: 50
[P - 17:31:12] [Transferring Pokemons] Transferring Pokemon away: Oddish (CP: 386)!
[P - 17:31:13] [Transferring Pokemons] Oddish has been transferred
[P - 17:31:16] [Farm Pokestops] Populated Pokestops
[P - 17:31:16] [Navigation] Walking from: 40.78386, -73.96997 to: 40.78312, -73.97108 with a distance of: 77 meters
[P - 17:31:26] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 17:31:28] [Catch Pokemon] We caught a Oddish (Probability: 93.85%) with CP 113, used 1 x ItemPokeBall and received 210 XP
[P - 17:31:43] [Farm Pokestops] Spinning Pokestop: 'Caduceus Woman'
[P - 17:31:43] [Transferring Pokemons] Transferring Pokemon away: Oddish (CP: 113)!
[P - 17:31:43] [Farm Pokestops] Success -> Received XP: 50
[P - 17:31:43] [Transferring Pokemons] Oddish has been transferred
[P - 17:31:44] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 17:31:45] [Catch Pokemon] We caught a Poliwag (Probability: 92.71%) with CP 55, used 1 x ItemPokeBall and received 210 XP
[P - 17:31:49] [Catch Pokemon] No Pokemon nearby
[P - 17:31:53] [Farm Pokestops] Populated Pokestops
[P - 17:31:53] [Catch Pokemon] Catching a lured pokemon...
[P - 17:31:53] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 17:31:54] [Catch Pokemon] Berry has been successfully used
[P - 17:31:54] [Catch Pokemon] We caught a Pidgey (Probability: 32.67%) with CP 334, used 1 x ItemPokeBall and received 210 XP
[P - 17:31:55] [Navigation] Walking from: 40.78326, -73.97086 to: 40.78285, -73.97126 with a distance of: 36 meters
[P - 17:32:01] [Farm Pokestops] Spinning Pokestop: 'The Alden Crest'
[P - 17:32:02] [Farm Pokestops] Success -> Received XP: 50
[P - 17:32:06] [Navigation] Walking from: 40.78302, -73.9711 to: 40.78296, -73.97202 with a distance of: 48 meters
[P - 17:32:14] [Transferring Pokemons] Transferring Pokemon away: Pidgey (CP: 334)!
[P - 17:32:15] [Transferring Pokemons] Pidgey has been transferred
[P - 17:32:19] [Farm Pokestops] Spinning Pokestop: 'Cherub Gate'
[P - 17:32:19] [Farm Pokestops] Success -> Received XP: 50
[P - 17:32:20] [Transferring Pokemons] Transferring Pokemon away: Poliwag (CP: 55)!
[P - 17:32:20] [Transferring Pokemons] Poliwag has been transferred
[P - 17:32:21] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 17:32:21] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 17:32:22] [Catch Pokemon] Berry has been successfully used
[P - 17:32:22] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 17:32:23] [Catch Pokemon] Berry has been successfully used
[P - 17:32:24] [Catch Pokemon] We caught a Raticate (Probability: 17.29%) with CP 461, used 2 x ItemPokeBall and received 210 XP
[P - 17:32:28] [Catch Pokemon] No Pokemon nearby
[P - 17:32:51] [Transferring Pokemons] Transferring Pokemon away: Raticate (CP: 461)!
[P - 17:32:51] [Transferring Pokemons] Raticate has been transferred
[P - 17:32:53] [Catch Pokemon] No Pokemon nearby
[P - 17:33:17] [Catch Pokemon] No Pokemon nearby
[P - 17:33:22] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 17:33:36] [Catch Pokemon] No Pokemon nearby
[P - 17:33:47] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 17:33:52] [Catch Pokemon] No Pokemon nearby
[P - 17:34:08] [Catch Pokemon] No Pokemon nearby
[P - 17:34:12] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...

**Comment by T2HotZero** [comment]
so basically 3 minutes

**Comment by DatFIXER** [comment]
Crazy o.O! Mine still working, maybe a fix update is needed at this point @finndev @EloBuddyLtd

**Comment by T2HotZero** [comment]
Makes no sense man.... *cries* All I wanted was a damn husky Dragonite LOL

**Comment by T2HotZero** [comment]
@DatFIXER This is new

[P - 17:37:32] Retrying request https://pgorelease.nianticlabs.com/plfe/95/rpc

**Comment by T2HotZero** [comment]
@DatFIXER Just started working again?!? WTF

**Comment by DatFIXER** [comment]
MMLMLMLML Idk, gratz tho XD!! Maybe was Niantics having prob idk!

**Comment by T2HotZero** [comment]
No man i spoke to soon, stopped soon after lol

**Comment by BoatGravy57** [comment]
It worked for 19 minutes and then stopped :( idk how to use vpn or whatever, and i dont think reseting our router would work. So i guess no more botting for me

**Comment by tivgnos** [comment]
@DatFIXER  I found problem. It slow walking and farming and then put exception on these below.

[P - 08:52:35] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:52:37] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:53:45] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:53:45] [Farm Pokestops - ERROR]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at i\&3TB E8T1J h\]n\&ho2;~:z(".kFN9LrFcX)amcLhHt\]1\\\[3'6%`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at i\&3TB E8T1J h\]n\&ho2;~:z(".fHy!Dk\&\,Peq^Q"A"vNrlgA<K!`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at fP?XWN1cDX'p-8\.wyhf\[;yat%.l8\\uyX z2lk\&OYy/^1zc{>hK`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at  H4g`k|U1= `'D>y7_\]\,}WU<!.6kkyk>K~V{SNO7\*:\]ma'$$Ed'.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at 3/:^L7Gv!a3ic'"RCaDT4#AT(.afomVA"xEE\*Fo;"05OFy(uam!.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 08:53:47] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:53:47] [Farm Pokestops] Populated Pokestops
[P - 08:53:47] [Navigation] Walking from: 13.74542, 100.53169 to: 13.74494, 100.53162 with a distance of: 33 meters
[P - 08:54:09] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:54:38] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:54:41] [Farm Pokestops] Spinning Pokestop: 'Red Garuda'
[P - 08:54:42] [Farm Pokestops] Success -> Received XP: 50
[P - 08:54:46] [Farm Pokestops] Populated Pokestops
[P - 08:54:47] [Navigation] Walking from: 13.74513, 100.53165 to: 13.74472, 100.53222 with a distance of: 48 meters
[P - 08:55:42] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:56:52] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:56:52] [Farm Pokestops - ERROR]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at i\&3TB E8T1J h\]n\&ho2;~:z(".kFN9LrFcX)amcLhHt\]1\\\[3'6%`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at i\&3TB E8T1J h\]n\&ho2;~:z(".fHy!Dk\&\,Peq^Q"A"vNrlgA<K!`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at fP?XWN1cDX'p-8\.wyhf\[;yat%.l8\\uyX z2lk\&OYy/^1zc{>hK`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at  H4g`k|U1= `'D>y7_\]\,}WU<!.6kkyk>K~V{SNO7\*:\]ma'$$Ed'.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at 3/:^L7Gv!a3ic'"RCaDT4#AT(.afomVA"xEE\*Fo;"05OFy(uam!.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 08:56:54] [Farm Pokestops] Populated Pokestops
[P - 08:56:54] [Navigation] Walking from: 13.7451, 100.53168 to: 13.74553, 100.5317 with a distance of: 30 meters
[P - 08:56:56] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
[P - 08:57:28] Stopping...
[P - 08:57:39] Retrying request https://pgorelease.nianticlabs.com/plfe/52/rpc
