### ISSUE TITLE
 [Farm Pokestops - ERROR]: System.ArgumentNullException:

### ISSUE THREAD

**Issue by sasayou1** [finndev/PokeBuddy#87]
[P - 06:44:42] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

help　me

**Comment by Vanethir** [comment]
Should be solved with recent updates. Try to reinstall a fresh version. :)
