### ISSUE TITLE
Bot Not Working

### ISSUE THREAD

**Issue by Adwaree** [finndev/PokeBuddy#882]
My pokebuddy stopped working today and i dont know why. Yes, I have made sure i'm not soft or ip banned. Whenever i try to use the bot it says this in the console.

[P - 16:30:04] [Catch Pokemon] Catching a lured pokemon...
[P - 16:30:04] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SYF0j8/!> Nn\\1%P#'N{yTXk".R^eLH%\,rP\\5 DD`CY(YT9`\\/%.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SYF0j8/!> Nn\\1%P#'N{yTXk".p aDb\*Rqjx<}A})E\\^'<`'8T.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()
[P - 16:30:05] Stopping...

**Comment by DatFIXER** [comment]
#863 
Had same issue couple of days ago, try, and if needed do a fresh installation

**Comment by shiitan5** [comment]
none of those works

**Comment by DatFIXER** [comment]
@shiitan5 he hasn't the same issue as you have... cmon...

**Comment by Adwaree** [comment]
@DatFIXER I reinstalled 4 times and still get the same error. Also tried alt accounts and nothing.
